config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'home#index'
  get 'people' => 'people#index'

  root to: redirect('/home')

  resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    def index
        @people = Person.order('first_name')
    end
    
    def new
        @person = Person.new
    end
    
    def create
        @person = Person.new person_params
        if @person.save
            redirect_to people_path
        else
            render :new
        end
    end
    
    def edit
        @person = Person.find_by id: params[:id]
    end
    
    def update
        @person = Person.find_by id: params[:id]
        @person.update_attributes person_params
        redirect_to people_url
    end
    
    def show
        @person = Person.find_by id: params[:id]
    end
    
private
    
    def person_params
        params[:person].permit(:first_name,:last_name,:nickname,:picture,:description,:gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class='container-fluid hero-container'>
    <div class='row'>
        <div class='col-2'></div>
        <div class='col-8 hero-text'>People Everywhere...</div>
        <div class='col-2'></div>
    </div>
</div>
<div class='container-fluid tools-container'>
    <div class='row'>
        <div class='col-xs-12 col-sm-12 col-md-12 col-lg-4 icon'>
            <div class="justify-content-center"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 48 48" xml:space="preserve" class='svg people-svg'>
<path d="M33,24c2.8,0,5-2.2,5-5s-2.2-5-5-5s-5,2.2-5,5S30.2,24,33,24z M18,22c3.3,0,6-2.7,6-6s-2.7-6-6-6s-6,2.7-6,6S14.7,22,18,22z
	 M33,28c-3.7,0-11,1.8-11,5.5V38h22v-4.5C44,29.8,36.7,28,33,28z M18,26c-4.7,0-14,2.3-14,7v5h14v-4.5c0-1.7,0.7-4.7,4.7-6.9
	C21,26.2,19.3,26,18,26z"/>
</svg></div>
            <h5 class="display-5">Find And Add People</h4>
            <p>Search for people in the database or add people to it.</p>
        </div>
        <div class='col-xs-12 col-sm-12 col-md-12 col-lg-4 icon'>
            <div class="justify-content-center"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 48 48" xml:space="preserve" class='svg chat-svg'>
<path d="M42 12h-4v18H12v4c0 1.1.9 2 2 2h22l8 8V14c0-1.1-.9-2-2-2zm-8 12V6c0-1.1-.9-2-2-2H6c-1.1 0-2 .9-2 2v28l8-8h20c1.1 0 2-.9 2-2z"/>
</svg></div>
            <h5 class="display-5">Chat with People</h4>
            <p>Find and chat with people who have a registered account.</p>
        </div>
        <div class='col-xs-12 col-sm-12 col-md-12 col-lg-4 icon'>
            <div class="justify-content-center"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
            viewBox="0 0 48 48" xml:space="preserve" class='svg image-svg'>
<path d="M6 8V2h4v6h6v4h-6v6H6v-6H0V8h6zm6 12v-6h6V8h14l3.66 4H42c2.2 0 4 1.8 4 4v24c0 2.2-1.8 4-4 4H10c-2.2 0-4-1.8-4-4V20h6zm14 18c5.52 0 10-4.48 10-10s-4.48-10-10-10-10 4.48-10 10 4.48 10 10 10zm-6.4-10c0 3.54 2.86 6.4 6.4 6.4s6.4-2.86 6.4-6.4-2.86-6.4-6.4-6.4-6.4 2.86-6.4 6.4z"/>
</svg></div>
            <h5 class="display-5">Upload Images</h4>
            <p>Upload images for people and your account.</p>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>People Info</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <script>
  $(document).on('click',function(){
    $('.collapse').collapse('hide');
  })
  </script> 
  <nav class="navbar navbar-toggleable-md navbar-inverse nav-bg">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'People Info', root_url, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', home_path, class: "nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to 'People', people_path, class: "nav-link" %>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search For People...">
      <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<%= yield %>
<div class="container-fluid footer">
  <div class='row'>
    <div class='col-1 hidden-xs-down'><%= link_to 'Home', home_path, class: "nav-link" %></div>
    <div class='col-1 hidden-xs-down'><%= link_to 'People', people_path, class: "nav-link" %></div>
    <div class='col'><p class='copyright'>Copyright Bradley Harker 2017</p></div>
  </div>
</div>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</html>

app/views/people/_form.html.erb
<div class="text-danger">
  <ul>
    <% @person.errors.messages.each_pair do |attr, errors| %>
      <li><%= attr %> <%= errors.to_sentence %></li>
    <% end %>
  </ul>
</div>

<%= form_for @person do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, placeholder: "Nickname", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="form-check form-check-inline">
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, 'Male', class: 'custom-control-input' %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Male</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, 'Female', class: 'custom-control-input' %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Female</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, 'Other', class: 'custom-control-input' %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Other</span>
    </label>
  </div>
  <% { picture: 'Picture'}.each_pair do |attr, label| %>
  <div class='form-group'>
    <%= f.label attr, label %>
    <% if @person.send(attr).present? %>
      <div>
        <%= image_tag @person.send(attr).url, class: 'img-fluid' %>
      </div>
    <% end %>
    <%= f.file_field attr, accept: "image/gif, image/jpeg, image/png", class: 'form-control' %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-outline-primary' %>
    <a href="/people" class='btn btn-link'>Cancel</a>
  </div>
<% end %>

app/views/people/edit.html.erb
<h4 class='display-4'>Edit Person</h4>
<%= render "form" %>

app/views/people/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <h4 class="display-4">People</h4>
    </div>
    <div class="col align-self-center">
      <%= link_to 'New Person', new_person_path, class: 'btn  btn-outline-primary pull-right' %>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="row">
    <% @people.each do |person| %>
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
        <div class="container-fluid person">
          <div class="row">
            <div class="col">
              <%= image_tag person.send(:picture).url, class: 'img-fluid' %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h4><strong><%= person.first_name %> <%= person.last_name %></strong></h4>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <h4><small><%= person.description %></small></h4>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= link_to 'view', person, class: "btn btn-link" %>
            </div>
            <div class="col">
              <%= link_to 'edit', edit_person_path(person), class: "btn btn-link" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/people/new.html.erb
<h4 class='display-4'>Create New Person</h4>
<%= render "form" %>

app/views/people/show.html.erb
<div class='container-fluid'>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-8">
            <h1><%= @person.first_name %> <%= @person.last_name %></h1>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-4">
            <%= image_tag @person.send(:picture).url, class: 'img-fluid' %>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p>
                My name is <%= @person.first_name %> <%= @person.last_name %>, but people call me <%= @person.nickname %>. <%= @person.description %>
            </p>
        </div>
    </div>
</div>